### ISSUE TITLE
Error message vcovfunc

### ISSUE THREAD

**Issue by thelma1600** [cran/RESI#1]
Hey,

I have calculated a two-factor robust mixed anova with the function bwtrim from the WRS2 package. I would now like to calculate the effect sizes for the output of the anova. Unfortunately, my data does not seem to be in the appropriate form for the resi() function. In which format do I have to bring my data to be able to use your function? Or is this not possible at all with the bwtrim anova?
I keep getting the following error message:

> mixedanova <- WRS2::bwtrim(formula = value ~ group*situation, id = id, data = data.long)
> resi_obj <- resi(mixedanova)

Error: Model type not implemented in RESI package, attempting defaultUpdating model fit failed. Try running with providing data argument
Error: Fitting intercept-only model failed. No overall test computedWarnung: Model type not implemented in RESI package, attempting defaultError in value[[3L]](cond) : Computing covariance failed. Trying running with different function for vcovfunc

I would be very grateful for your help!

[data.csv](https://github.com/cran/RESI/files/12324167/data.csv)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
